export default {
    GET_LIST:"GET_LIST",
    SET_LIST:"SET_LIST",
    CHANGE_INFORM_TITLE:"CHANGE_INFORM_TITLE",
    SET_ALL_READ:"SET_ALL_READ",
    SET_READ_BY_ID:"SET_READ_BY_ID",
    START_LOGIN:"START_LOGIN",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_ERR:"LOGIN_ERR"
}